name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          configuration: .github/changelog-config.json
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          append_body: true
          body: ${{ steps.build_changelog.outputs.changelog }}
